# goreleaser release --clean --snapshot

version: 2

project_name: zirva
builds:
  - main: ./cmd/server/
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    binary: "{{ .ProjectName }}-{{ if eq .Arch \"amd64\" }}x86_64{{ else if eq .Arch \"386\" }}i386{{ else }}{{ .Arch }}{{ end }}"

checksum:
  disable: true
archives:
  - format: binary